front-builder.com/config/routes.rb
FrontBuilder::Application.routes.draw do
  resources :adventures
  devise_for :users
  root to: 'welcome#index'

end

front-builder.com/app/models/adventure.rb
class Adventure < ActiveRecord::Base
  attr_accessible :description, :title, :dangers_attributes
  validates_presence_of :title
  has_many :dangers, dependent: :destroy
  accepts_nested_attributes_for :dangers, reject_if: :all_blank, allow_destroy: true
end

front-builder.com/app/models/danger.rb
class Danger < ActiveRecord::Base
  belongs_to :adventure
  attr_accessible :impending_doom, :impulse, :title, :grim_portents_attributes
  validates_presence_of :title
  has_many :grim_portents, dependent: :destroy
  accepts_nested_attributes_for :grim_portents, reject_if: :all_blank, allow_destroy: true
end

front-builder.com/app/models/grim_portent.rb
class GrimPortent < ActiveRecord::Base
  belongs_to :danger
  attr_accessible :complete, :description, :danger_id
end

front-builder.com/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

front-builder.com/app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  before_filter :set_adventure, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @adventures = Adventure.all
    respond_with(@adventures)
  end

  def show
    respond_with(@adventure)
  end

  def new
    @adventure = Adventure.new
    respond_with(@adventure)
  end

  def edit
  end

  def create
    @adventure = Adventure.new(params[:adventure])
    @adventure.save
    respond_with(@adventure)
  end

  def update
    @adventure.update_attributes(params[:adventure])
    respond_with(@adventure)
  end

  def destroy
    @adventure.destroy
    respond_with(@adventure)
  end

  private
    def set_adventure
      @adventure = Adventure.find(params[:id])
    end
end

front-builder.com/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

front-builder.com/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

front-builder.com/app/helpers/adventures_helper.rb
module AdventuresHelper
  def link_to_add_fields(partial_name, copy, form, association)
    new_object = form.object.send(association).klass.new
    id = new_object.object_id
    fields = form.fields_for(association, new_object, child_index: id) do |builder|
      render partial: partial_name, locals: {f: builder} 
    end

    link_to '#', class: 'add-fields', data: {id: id, fields: fields.gsub('\n', '')}  do
      button_tag type: 'button', class: 'button tiny' do
        content_tag :span, copy
      end
    end
  end
end

front-builder.com/app/helpers/application_helper.rb
module ApplicationHelper
  def nav_links
    links = [] 

    if user_signed_in?
      links << link_to('Adventures', :adventures)
      links << link_to('Settings', :edit_user_registration)
      links << link_to('Sign Out', :destroy_user_session, method: :delete)
    else
      links << link_to('Sign In', :new_user_session)
    end

    links
  end
end

front-builder.com/app/helpers/welcome_helper.rb
module WelcomeHelper
end

front-builder.com/app/views/adventures/_form.html.erb
<% if @adventure.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@adventure.errors.count, "error") %> prohibited this adventure from being saved:
    </h2>

    <ul>
      <% @adventure.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="white-panel">
  <%= form_for(@adventure) do |f| %>
    <div class="actions left">
      <%= f.submit 'Save Adventure', class: 'button success tiny' %>
    </div>

    <div class="text-right">
      <%= link_to @adventure do %>
        <%= button_tag type: 'button', class: 'button tiny warning' do %>
          <%= content_tag :span, 'Cancel' %>
        <% end %>
      <% end %>
    </div>

    <div class="field" style="margin-top: 10px;">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description %>
    </div>
    <hr>

    <%= link_to_add_fields 'dangers/fields', 'Add Danger', f, :dangers %>
    <ul class="accordion add-fields-wrapper" data-accordion>
      <%= f.fields_for :dangers do |builder| %>
        <%= render partial: 'dangers/fields', locals: {f: builder} %>
      <% end %>
    </ul>
  <% end %>
</div>

front-builder.com/app/views/adventures/edit.html.erb
<div class="row">
  <div class="large-8 large-offset-2 columns">
    <%= render 'form' %>
  </div>
</div>

front-builder.com/app/views/adventures/index.html.erb
<div class="row">
  <div class="large-4 columns">
    <%= link_to new_adventure_path do %>
      <%= button_tag type: 'button', class: 'button tiny success' do %>
        <%= content_tag :span, 'New Adventure' %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="row" style="padding-top: 20px;">
  <% if @adventures.any? -%>
    <% @adventures.each do |adventure| %>
      <%= link_to adventure_path(adventure) do %>
        <div class="large-4 columns">
          <div class="panel">
            <h3 class="text-center">
              <%= truncate adventure.title, length: 20 %>     
            </h3>
            <hr>
            <div class="text-center">
              <b>
                <%= pluralize adventure.dangers.count, 'danger' %>
              </b>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <div class="text-center">
      <p>No Adventures found.</p>
    </div>
  <% end %>
</div>

front-builder.com/app/views/adventures/new.html.erb
<div class="row">
  <div class="large-8 large-offset-2 columns">
    <%= render 'form' %>
  </div>
</div>

front-builder.com/app/views/adventures/show.html.erb
<div class="row">
  <div class="large-8 large-offset-2 columns white-panel">
    <p id="notice"><%= notice %></p>

    <div class="left">
      <%= link_to edit_adventure_path(@adventure) do %>
        <%= button_tag type: 'button', class: 'button tiny warning' do %> 
          <%= content_tag :span, 'Edit' %>
        <% end %>
      <% end %>
    </div>

    <div class="text-right">
      <%= button_to 'Delete', @adventure, method: :delete, confirm: 'Are you sure?', class: 'button tiny alert' %>
    </div>

    <p>
      <b>Title:</b>
      <%= @adventure.title %>
    </p>

    <p>
      <b>Description:</b>
      <%= @adventure.description %>
    </p>

    <p>
      <b>Dangers:</b>
      <% if @adventure.dangers.any? -%>
        <ul class="accordion" data-accordion>
          <% @adventure.dangers.each do |danger| -%>
              <%= render partial: 'dangers/list_item', locals: {danger: danger} %>
          <% end %>
        </ul>
      <% else %>
        <i>No dangers found.</i>
      <% end %>
    </p>

  </div>
</div>

front-builder.com/app/views/dangers/_fields.html.erb
<li class="accordion-navigation remove-fields-wrapper">
  <a href="#panel-<%= f.object.id || f.object.object_id %>">
    <%= f.object.title || 'New Danger' %>
    <%= button_tag 'Delete Danger', type: 'button', class: 'button alert tiny right remove-fields' %>
  </a>
  <div id="panel-<%= f.object.id || f.object.object_id %>" class="content">
    <fieldset>
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :impulse %>
        <%= f.text_field :impulse %>
      </div>
      <div class="field">
        <%= f.label :impending_doom %>
        <%= f.text_field :impending_doom %>
      </div>

      <%= f.hidden_field :_destroy %>

      <hr>

      <%= link_to_add_fields 'grim_portents/fields', 'Add Grim Portent', f, :grim_portents %>
      <div id="portent-panel" class="content add-fields-wrapper">
        <%= f.fields_for :grim_portents do |builder| %>
          <%= render partial: 'grim_portents/fields', locals: {f: builder} %>
        <% end %>
      </div>
    </fieldset>
  </div>
</li>

front-builder.com/app/views/dangers/_list_item.html.erb
<li class="accordion-navigation">
  <a href="#panel-<%= danger.id %>">
    <%= danger.title %>
  </a>
  <div id="panel-<%= danger.id %>" class="content">
    <%= debug danger %>
    <%= debug danger.grim_portents %>
  </div>
</li>

front-builder.com/app/views/grim_portents/_fields.html.erb
<div class="row collapse remove-fields-wrapper">
  <div class="small-1 columns">
    <div class="field">
      <%= f.check_box :complete, class: 'inline' %>
    </div>
  </div>
  <div class="small-10 columns"> 
    <div class="field">
      <%= f.text_field :description, placeholder: 'Grim Portent' %>
    </div>
  </div>
  <div class="small-1 columns">
    <%= content_tag :a, href: '#', class: 'button alert postfix remove-fields' do %>
      x
    <% end %>
  </div>
</div>

front-builder.com/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Front Builder" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1>
            <%= link_to :root do %>
              <span>Front Builder</span>
            <% end %>
          </h1>
        </li>

        <li class="toggle-topbar menu-icon">
          <a href="#">
            <span></span>
          </a>
        </li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <% nav_links.each do |link| -%>
            <li>
              <%= link %>
            </li>
          <% end -%>
        </ul> 
      </section>
    </nav>

    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

front-builder.com/app/views/welcome/index.html.erb
<div class="row">
  <div class="splash text-center">
    <h1>front-builder</h1>
    <p class="tag-line">
      Build and manage your Dungeon World campaigns.
    </p>
  </div>
</div>